---
all:
  children:
    microk8s_cluster:
      children:
        microk8s_master:
          hosts:
            raspi-master:
              ansible_host: 192.168.1.100
        microk8s_workers:
          hosts:
            raspi-worker-1:
              ansible_host: 192.168.1.101
              # raspi-worker-2:
              #   ansible_host: 192.168.1.102
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    # base role
    # base_hostname: override per host if needed
    # base_timezone: Europe/Paris
    # microk8s role
    # microk8s_channel: "1.30/stable"
