FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/root

RUN apt-get update && apt-get install -y \
    systemd \
    python3 \
    python3-apt \
    sudo \
    gnupg \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /tmp/.ansible/tmp

CMD ["/lib/systemd/systemd"]
