FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    systemd \
    python3 \
    python3-apt \
    sudo \
    gnupg \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["/lib/systemd/systemd"]
