---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: raspi-test
    image: debian:bookworm
    dockerfile: Dockerfile.j2
    pre_build_image: false
    command: sleep infinity

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      raspi-test:
        ansible_user: root
        molecule_test: true
  env:
    ANSIBLE_ROLES_PATH: ../../roles

verifier:
  name: ansible
